---
name: deploy website
on:
  workflow_dispatch: {}
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write

jobs:
  upload-website:
    uses: acidbrun0zzz/publicsuffix-list/.github/workflows/deploy-site.yaml@master
    secrets: inherit
